### ISSUE TITLE
Question: Query Expression Constraint/Validation

### ISSUE THREAD

**Issue by espray** [eugenpaval/graphql-linq-sample#1]
Thanks for posting this sample! 👍 

Next problem :)
Any ideas on how you could constrain the expression to specific properties?
Only way I can think of is an Expression Visitor.

Example
products.where() -- Only allow 'id' and/or 'category'
products.orderBy() -- Only allow 'name'

```
type Products
{
	where(exp: String!): Products!
	orderBy(exp: String!): Products!

	select(start: Int = -1, count: Int = -1): [Product!]!
}

type Product
{
	id: ID!
	name: String!
	category: String!
	price: Decimal!
}
```

**Comment by eugenpaval** [comment]
Parameters are simple strings so the schema won't be able to validate any constraints. You can possibly validate the query at runtime as you said by inspecting the expressions generated by the dynamic linq library.
